BEGIN;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS two_factor_secret text,
    ADD COLUMN IF NOT EXISTS two_factor_confirmed_at timestamptz;

CREATE TABLE IF NOT EXISTS sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash char(64) NOT NULL UNIQUE,
    remember_me boolean NOT NULL DEFAULT false,
    device_name text,
    ip_address inet,
    user_agent text,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON sessions (user_id);
CREATE INDEX IF NOT EXISTS sessions_expires_at_idx ON sessions (expires_at);

CREATE TABLE IF NOT EXISTS legacy_passwords (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name text NOT NULL,
    token_hash char(64) NOT NULL UNIQUE,
    token_prefix text NOT NULL,
    scopes text[] NOT NULL DEFAULT ARRAY['catalog:read', 'downloads:read']::text[],
    last_used_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS legacy_passwords_user_id_idx ON legacy_passwords (user_id);

CREATE TABLE IF NOT EXISTS legacy_devices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    legacy_password_id bigint REFERENCES legacy_passwords(id) ON DELETE SET NULL,
    device_identifier text,
    device_name text,
    last_ip inet,
    last_user_agent text,
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS legacy_devices_user_id_idx ON legacy_devices (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS legacy_devices_identifier_unique
    ON legacy_devices (user_id, device_identifier)
    WHERE device_identifier IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS reviews_one_active_per_user_app
    ON reviews (app_id, user_id)
    WHERE deleted_at IS NULL;

COMMIT;
