BEGIN;

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    password_hash text,
    nickname text,
    avatar_url text,
    email_verified boolean NOT NULL DEFAULT false,
    two_factor_enabled boolean NOT NULL DEFAULT false,
    status text NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT users_status_check CHECK (status IN ('active', 'disabled', 'pending'))
);

CREATE UNIQUE INDEX users_email_lower_unique ON users (lower(email));

CREATE TABLE roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT roles_name_check CHECK (name IN ('guest', 'user', 'trusted', 'moder', 'admin'))
);

INSERT INTO roles (name)
VALUES ('guest'), ('user'), ('trusted'), ('moder'), ('admin')
ON CONFLICT (name) DO NOTHING;

CREATE TABLE user_roles (
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id bigint NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    name text NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE apps (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    name text NOT NULL,
    bundle_id text,
    developer_name text NOT NULL,
    summary text NOT NULL,
    description text,
    website_url text,
    license_type text,
    created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    moderation_status text NOT NULL DEFAULT 'pending',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT apps_moderation_status_check CHECK (moderation_status IN ('pending', 'approved', 'rejected'))
);

CREATE UNIQUE INDEX apps_bundle_id_unique ON apps (bundle_id) WHERE bundle_id IS NOT NULL;
CREATE INDEX apps_moderation_status_idx ON apps (moderation_status);

CREATE TABLE app_categories (
    app_id bigint NOT NULL REFERENCES apps(id) ON DELETE CASCADE,
    category_id bigint NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    PRIMARY KEY (app_id, category_id)
);

CREATE TABLE app_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id bigint NOT NULL REFERENCES apps(id) ON DELETE CASCADE,
    version text NOT NULL,
    release_date date,
    changelog text,
    is_recommended boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (app_id, version)
);

CREATE INDEX app_versions_app_id_idx ON app_versions (app_id);

CREATE TABLE artifacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_version_id bigint NOT NULL REFERENCES app_versions(id) ON DELETE CASCADE,
    file_name text NOT NULL,
    package_type text NOT NULL,
    source_type text NOT NULL,
    storage_path text,
    primary_download_url text,
    torrent_url text,
    magnet_url text,
    size_bytes bigint,
    sha256 char(64),
    min_os text NOT NULL DEFAULT '10.5',
    max_supported_os text,
    max_tested_os text,
    hard_block_above_max boolean NOT NULL DEFAULT false,
    arch_i386 boolean NOT NULL DEFAULT false,
    arch_x86_64 boolean NOT NULL DEFAULT true,
    supports_32bit boolean NOT NULL DEFAULT true,
    supports_64bit boolean NOT NULL DEFAULT true,
    requires_rosetta boolean NOT NULL DEFAULT false,
    requires_java boolean NOT NULL DEFAULT false,
    install_notes text,
    moderation_status text NOT NULL DEFAULT 'pending',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT artifacts_package_type_check CHECK (package_type IN ('app', 'dmg', 'zip', 'pkg', 'iso', 'other')),
    CONSTRAINT artifacts_source_type_check CHECK (source_type IN ('local', 'external_direct', 'external_page')),
    CONSTRAINT artifacts_moderation_status_check CHECK (moderation_status IN ('pending', 'approved', 'rejected')),
    CONSTRAINT artifacts_size_bytes_check CHECK (size_bytes IS NULL OR size_bytes >= 0),
    CONSTRAINT artifacts_sha256_check CHECK (sha256 IS NULL OR sha256 ~ '^[0-9a-fA-F]{64}$'),
    CONSTRAINT artifacts_arch_check CHECK (arch_i386 OR arch_x86_64),
    CONSTRAINT artifacts_bitness_check CHECK (supports_32bit OR supports_64bit)
);

CREATE INDEX artifacts_app_version_id_idx ON artifacts (app_version_id);
CREATE INDEX artifacts_moderation_status_idx ON artifacts (moderation_status);

CREATE TABLE artifact_mirrors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_id bigint NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE,
    mirror_type text NOT NULL,
    url text NOT NULL,
    priority integer NOT NULL DEFAULT 100,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT artifact_mirrors_type_check CHECK (mirror_type IN ('http', 'official', 'external_page', 'web_seed'))
);

CREATE INDEX artifact_mirrors_artifact_id_idx ON artifact_mirrors (artifact_id);

CREATE TABLE icons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id bigint NOT NULL REFERENCES apps(id) ON DELETE CASCADE,
    app_version_id bigint REFERENCES app_versions(id) ON DELETE CASCADE,
    image_url text NOT NULL,
    min_os text NOT NULL DEFAULT '10.5',
    max_os text NOT NULL DEFAULT '15',
    width integer,
    height integer,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT icons_width_check CHECK (width IS NULL OR width > 0),
    CONSTRAINT icons_height_check CHECK (height IS NULL OR height > 0)
);

CREATE INDEX icons_app_id_idx ON icons (app_id);
CREATE INDEX icons_app_version_id_idx ON icons (app_version_id);

CREATE TABLE screenshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id bigint NOT NULL REFERENCES apps(id) ON DELETE CASCADE,
    app_version_id bigint REFERENCES app_versions(id) ON DELETE CASCADE,
    image_url text NOT NULL,
    min_os text NOT NULL DEFAULT '10.5',
    max_os text NOT NULL DEFAULT '15',
    caption text,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX screenshots_app_id_idx ON screenshots (app_id);
CREATE INDEX screenshots_app_version_id_idx ON screenshots (app_version_id);

CREATE TABLE reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id bigint NOT NULL REFERENCES apps(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    rating integer NOT NULL,
    title text,
    body text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT reviews_rating_check CHECK (rating BETWEEN 1 AND 5)
);

CREATE INDEX reviews_app_id_idx ON reviews (app_id);
CREATE INDEX reviews_user_id_idx ON reviews (user_id);

CREATE TABLE review_replies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id bigint NOT NULL REFERENCES reviews(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE INDEX review_replies_review_id_idx ON review_replies (review_id);

CREATE TABLE review_likes (
    review_id bigint NOT NULL REFERENCES reviews(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (review_id, user_id)
);

CREATE TABLE moderation_queue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type text NOT NULL,
    entity_id text NOT NULL,
    submitted_by bigint REFERENCES users(id) ON DELETE SET NULL,
    status text NOT NULL DEFAULT 'pending',
    moderator_id bigint REFERENCES users(id) ON DELETE SET NULL,
    moderator_comment text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT moderation_queue_status_check CHECK (status IN ('pending', 'approved', 'rejected'))
);

CREATE INDEX moderation_queue_status_idx ON moderation_queue (status);

CREATE TABLE audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    action text NOT NULL,
    entity_type text,
    entity_id text,
    ip_address inet,
    user_agent text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX audit_log_actor_user_id_idx ON audit_log (actor_user_id);
CREATE INDEX audit_log_created_at_idx ON audit_log (created_at);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER users_set_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER categories_set_updated_at BEFORE UPDATE ON categories FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER apps_set_updated_at BEFORE UPDATE ON apps FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER app_versions_set_updated_at BEFORE UPDATE ON app_versions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER artifacts_set_updated_at BEFORE UPDATE ON artifacts FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER artifact_mirrors_set_updated_at BEFORE UPDATE ON artifact_mirrors FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER icons_set_updated_at BEFORE UPDATE ON icons FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER screenshots_set_updated_at BEFORE UPDATE ON screenshots FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER reviews_set_updated_at BEFORE UPDATE ON reviews FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER review_replies_set_updated_at BEFORE UPDATE ON review_replies FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER moderation_queue_set_updated_at BEFORE UPDATE ON moderation_queue FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION enforce_single_admin_role()
RETURNS trigger AS $$
DECLARE
    admin_role_id bigint;
BEGIN
    SELECT id INTO admin_role_id FROM roles WHERE name = 'admin';

    IF admin_role_id IS NOT NULL AND NEW.role_id = admin_role_id THEN
        IF EXISTS (
            SELECT 1
            FROM user_roles
            WHERE role_id = admin_role_id
              AND user_id <> NEW.user_id
        ) THEN
            RAISE EXCEPTION 'only one user may have the admin role';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER user_roles_single_admin
BEFORE INSERT OR UPDATE ON user_roles
FOR EACH ROW EXECUTE FUNCTION enforce_single_admin_role();

COMMIT;
