BEGIN;

CREATE TABLE download_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_id bigint NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE,
    app_id bigint NOT NULL REFERENCES apps(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX download_events_app_created_at_idx
    ON download_events (app_id, created_at DESC);

CREATE INDEX download_events_artifact_created_at_idx
    ON download_events (artifact_id, created_at DESC);

COMMIT;
