BEGIN;

ALTER TABLE reviews
    ADD COLUMN public_uid varchar(22),
    ADD COLUMN app_version_id bigint REFERENCES app_versions(id) ON DELETE SET NULL,
    ADD COLUMN app_version text,
    ADD COLUMN os_version text,
    ADD COLUMN os_arch text,
    ADD COLUMN device_model text,
    ADD COLUMN client_version text,
    ADD COLUMN source text NOT NULL DEFAULT 'web';

UPDATE reviews
SET public_uid = substr(md5(id::text || ':' || created_at::text || ':' || random()::text), 1, 22)
WHERE public_uid IS NULL;

ALTER TABLE reviews
    ALTER COLUMN public_uid SET NOT NULL,
    ADD CONSTRAINT reviews_public_uid_length_check CHECK (char_length(public_uid) BETWEEN 16 AND 32),
    ADD CONSTRAINT reviews_body_length_check CHECK (body IS NULL OR char_length(body) <= 300) NOT VALID,
    ADD CONSTRAINT reviews_title_length_check CHECK (title IS NULL OR char_length(title) <= 120) NOT VALID,
    ADD CONSTRAINT reviews_os_arch_check CHECK (os_arch IS NULL OR os_arch IN ('i386', 'x86_64')),
    ADD CONSTRAINT reviews_source_check CHECK (source IN ('web', 'legacy', 'native'));

CREATE UNIQUE INDEX reviews_public_uid_unique ON reviews (public_uid);
CREATE INDEX reviews_app_version_id_idx ON reviews (app_version_id);

ALTER TABLE download_events
    ADD COLUMN app_version_id bigint REFERENCES app_versions(id) ON DELETE CASCADE,
    ADD COLUMN user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    ADD COLUMN username_snapshot text,
    ADD COLUMN ip_address inet,
    ADD COLUMN source text NOT NULL DEFAULT 'unknown',
    ADD COLUMN user_agent text,
    ADD COLUMN client_version text,
    ADD COLUMN os_version text,
    ADD COLUMN os_arch text,
    ADD COLUMN device_model text,
    ADD COLUMN completed_at timestamptz;

UPDATE download_events de
SET app_version_id = ar.app_version_id
FROM artifacts ar
WHERE ar.id = de.artifact_id
  AND de.app_version_id IS NULL;

ALTER TABLE download_events
    ADD CONSTRAINT download_events_source_check CHECK (source IN ('web', 'legacy', 'native', 'unknown')),
    ADD CONSTRAINT download_events_os_arch_check CHECK (os_arch IS NULL OR os_arch IN ('i386', 'x86_64'));

CREATE UNIQUE INDEX download_events_logged_unique
    ON download_events (artifact_id, user_id)
    WHERE user_id IS NOT NULL AND completed_at IS NOT NULL;

CREATE UNIQUE INDEX download_events_anonymous_ip_unique
    ON download_events (artifact_id, ip_address)
    WHERE user_id IS NULL AND ip_address IS NOT NULL AND completed_at IS NOT NULL;

CREATE INDEX download_events_completed_app_idx
    ON download_events (app_id, completed_at DESC)
    WHERE completed_at IS NOT NULL;

CREATE TABLE app_view_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id bigint NOT NULL REFERENCES apps(id) ON DELETE CASCADE,
    user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    username_snapshot text,
    ip_address inet,
    source text NOT NULL,
    user_agent text,
    client_version text,
    os_version text,
    os_arch text,
    device_model text,
    first_viewed_at timestamptz NOT NULL DEFAULT now(),
    last_viewed_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT app_view_events_source_check CHECK (source IN ('web', 'legacy', 'native')),
    CONSTRAINT app_view_events_os_arch_check CHECK (os_arch IS NULL OR os_arch IN ('i386', 'x86_64'))
);

CREATE UNIQUE INDEX app_view_events_logged_unique
    ON app_view_events (app_id, user_id)
    WHERE user_id IS NOT NULL;

CREATE UNIQUE INDEX app_view_events_anonymous_ip_unique
    ON app_view_events (app_id, ip_address)
    WHERE user_id IS NULL AND ip_address IS NOT NULL;

CREATE INDEX app_view_events_app_idx ON app_view_events (app_id, first_viewed_at DESC);

COMMIT;
