BEGIN;

ALTER TABLE roles DROP CONSTRAINT IF EXISTS roles_name_check;
ALTER TABLE roles
    ADD CONSTRAINT roles_name_check
    CHECK (name IN ('guest', 'user', 'uploader', 'trusted', 'moder', 'admin'));

INSERT INTO roles (name)
VALUES ('uploader')
ON CONFLICT (name) DO NOTHING;

ALTER TABLE apps
    ADD COLUMN source_url text;

ALTER TABLE artifacts
    ADD COLUMN architectures text[] NOT NULL DEFAULT ARRAY['x86_64']::text[];

UPDATE artifacts
SET architectures = CASE
    WHEN arch_i386 AND arch_x86_64 THEN ARRAY['i386', 'x86_64']::text[]
    WHEN arch_i386 THEN ARRAY['i386']::text[]
    WHEN arch_x86_64 THEN ARRAY['x86_64']::text[]
    ELSE ARRAY['x86_64']::text[]
END;

ALTER TABLE artifacts
    DROP CONSTRAINT IF EXISTS artifacts_arch_check,
    DROP CONSTRAINT IF EXISTS artifacts_bitness_check,
    DROP COLUMN arch_i386,
    DROP COLUMN arch_x86_64,
    DROP COLUMN supports_32bit,
    DROP COLUMN supports_64bit;

ALTER TABLE artifacts
    ADD CONSTRAINT artifacts_architectures_not_empty_check
        CHECK (cardinality(architectures) > 0),
    ADD CONSTRAINT artifacts_architectures_format_check
        CHECK (
            architectures <@ ARRAY['i386', 'i686', 'x86_64', 'ppc', 'ppc-g3', 'ppc-g4', 'ppc-g5', 'ppc64']::text[]
            AND array_position(architectures, NULL) IS NULL
        );

CREATE TABLE staged_uploads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_uid varchar(22) NOT NULL UNIQUE,
    app_id bigint NOT NULL REFERENCES apps(id) ON DELETE CASCADE,
    submitted_by bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    original_filename text NOT NULL,
    storage_path text NOT NULL UNIQUE,
    sha256 char(64) NOT NULL,
    size_bytes bigint NOT NULL,
    package_type text NOT NULL,
    detected_name text,
    detected_bundle_id text,
    detected_version text,
    detected_category_slug text,
    detected_min_os text,
    detected_architectures text[] NOT NULL DEFAULT ARRAY[]::text[],
    warnings jsonb NOT NULL DEFAULT '[]'::jsonb,
    status text NOT NULL DEFAULT 'staged',
    expires_at timestamptz NOT NULL DEFAULT (now() + interval '48 hours'),
    committed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT staged_uploads_uid_length_check CHECK (char_length(public_uid) BETWEEN 16 AND 32),
    CONSTRAINT staged_uploads_sha256_check CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT staged_uploads_size_check CHECK (size_bytes > 0),
    CONSTRAINT staged_uploads_package_type_check CHECK (package_type IN ('app', 'dmg', 'zip', 'pkg', 'iso', 'other')),
    CONSTRAINT staged_uploads_detected_architectures_format_check CHECK (
        detected_architectures <@ ARRAY['i386', 'i686', 'x86_64', 'ppc', 'ppc-g3', 'ppc-g4', 'ppc-g5', 'ppc64']::text[]
        AND array_position(detected_architectures, NULL) IS NULL
    ),
    CONSTRAINT staged_uploads_status_check CHECK (status IN ('staged', 'committed', 'abandoned'))
);

CREATE INDEX staged_uploads_app_id_idx ON staged_uploads (app_id);
CREATE INDEX staged_uploads_submitted_by_idx ON staged_uploads (submitted_by);
CREATE INDEX staged_uploads_status_expiry_idx ON staged_uploads (status, expires_at);

CREATE TRIGGER staged_uploads_set_updated_at
BEFORE UPDATE ON staged_uploads
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;
