BEGIN;

CREATE TABLE IF NOT EXISTS password_recovery_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash char(64) NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS password_recovery_tokens_user_id_idx
    ON password_recovery_tokens (user_id);
CREATE INDEX IF NOT EXISTS password_recovery_tokens_expires_at_idx
    ON password_recovery_tokens (expires_at);

CREATE TABLE IF NOT EXISTS two_factor_recovery_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    code_hash char(64) NOT NULL,
    used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, code_hash)
);

CREATE INDEX IF NOT EXISTS two_factor_recovery_codes_user_id_idx
    ON two_factor_recovery_codes (user_id);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS password_changed_at timestamptz,
    ADD COLUMN IF NOT EXISTS email_changed_at timestamptz;

COMMIT;
