BEGIN;

CREATE TABLE image_assets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_uid varchar(22) NOT NULL UNIQUE,
    kind text NOT NULL,
    storage_path text NOT NULL,
    mime_type text NOT NULL,
    file_ext text NOT NULL,
    original_filename text,
    size_bytes bigint NOT NULL,
    width integer NOT NULL,
    height integer NOT NULL,
    sha256 char(64) NOT NULL,
    created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT image_assets_uid_length_check CHECK (char_length(public_uid) BETWEEN 16 AND 32),
    CONSTRAINT image_assets_kind_check CHECK (kind IN ('avatar', 'review', 'screenshot', 'icon')),
    CONSTRAINT image_assets_size_check CHECK (size_bytes > 0 AND size_bytes <= 1048576),
    CONSTRAINT image_assets_dimensions_check CHECK (width > 0 AND height > 0 AND width <= 2048 AND height <= 2048),
    CONSTRAINT image_assets_sha256_check CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT image_assets_mime_check CHECK (mime_type IN ('image/jpeg', 'image/png', 'image/svg+xml'))
);

CREATE INDEX image_assets_created_by_idx ON image_assets (created_by);
CREATE INDEX image_assets_sha256_idx ON image_assets (sha256);

ALTER TABLE users
    ADD COLUMN avatar_image_id bigint REFERENCES image_assets(id) ON DELETE SET NULL;

ALTER TABLE icons
    ADD COLUMN image_asset_id bigint REFERENCES image_assets(id) ON DELETE SET NULL;

ALTER TABLE screenshots
    ADD COLUMN image_asset_id bigint REFERENCES image_assets(id) ON DELETE SET NULL;

CREATE TABLE review_images (
    review_id bigint NOT NULL REFERENCES reviews(id) ON DELETE CASCADE,
    image_id bigint NOT NULL REFERENCES image_assets(id) ON DELETE CASCADE,
    sort_order smallint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (review_id, image_id),
    UNIQUE (review_id, sort_order),
    CONSTRAINT review_images_sort_order_check CHECK (sort_order BETWEEN 0 AND 2)
);

CREATE INDEX review_images_image_id_idx ON review_images (image_id);

COMMIT;
