BEGIN;

ALTER TABLE artifacts
    ALTER COLUMN min_os SET DEFAULT '10.4';

ALTER TABLE icons
    ALTER COLUMN min_os SET DEFAULT '10.4';

ALTER TABLE screenshots
    ALTER COLUMN min_os SET DEFAULT '10.4';

COMMIT;
